// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI2Wln70fVaC33LQFEgakZSDkwudkVxXk',
    appId: '1:887418479403:web:1e265ab4ae5058c9e3db6e',
    messagingSenderId: '887418479403',
    projectId: 'safetrack-6382d',
    authDomain: 'safetrack-6382d.firebaseapp.com',
    storageBucket: 'safetrack-6382d.firebasestorage.app',
    measurementId: 'G-9YCZMCGRF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs-3dKwzun-S9WQCKrMcLxeREkG94f8fQ',
    appId: '1:887418479403:android:d0e2bdf659e5d558e3db6e',
    messagingSenderId: '887418479403',
    projectId: 'safetrack-6382d',
    storageBucket: 'safetrack-6382d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7PYMO9dsgWR6m5eNhXHRnnTxS1Q6IJP4',
    appId: '1:887418479403:ios:a22acd7429ffd7d8e3db6e',
    messagingSenderId: '887418479403',
    projectId: 'safetrack-6382d',
    storageBucket: 'safetrack-6382d.firebasestorage.app',
    iosBundleId: 'com.example.safeTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7PYMO9dsgWR6m5eNhXHRnnTxS1Q6IJP4',
    appId: '1:887418479403:ios:a22acd7429ffd7d8e3db6e',
    messagingSenderId: '887418479403',
    projectId: 'safetrack-6382d',
    storageBucket: 'safetrack-6382d.firebasestorage.app',
    iosBundleId: 'com.example.safeTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI2Wln70fVaC33LQFEgakZSDkwudkVxXk',
    appId: '1:887418479403:web:c4b4c3fa5be34c38e3db6e',
    messagingSenderId: '887418479403',
    projectId: 'safetrack-6382d',
    authDomain: 'safetrack-6382d.firebaseapp.com',
    storageBucket: 'safetrack-6382d.firebasestorage.app',
    measurementId: 'G-CKSP4JBDF6',
  );
}
